### ISSUE TITLE
Can't run as administrator

### ISSUE THREAD

**Issue by brunph** [MichaelKim/webview#1]
Whenever I run my webview executable as administrator the screen just gets white.

**Comment by MichaelKim** [comment]
Thanks for bringing this up! Unfortunately, it looks like this is a known issue for the EdgeHTML-powered webview without any solution:
- https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/32#issuecomment-442447380
- https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/13#issuecomment-520120466
- https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/63
- https://stackoverflow.com/a/59626878/2734517

**Comment by MichaelKim** [comment]
With the new Chromium-based Edge, the webview should be able to properly run as administrator.
