### ISSUE TITLE
Render to custom image buffer

### ISSUE THREAD

**Issue by zcream** [MichaelKim/webview#10]
Have you considered an API that will allow a render to an image buffer ? For embedded apps, showing a window is not necessary, and just drawing to RGBA buffer, and exposing the buffer is preferred.

**Comment by MichaelKim** [comment]
I haven't but that would be an interesting feature to have. The problem is it seems largely dependent on whether the underlying webviews (WebView2, WKWebview, WebkitGTK) support it. What kind of use cases do you have in mind?

**Comment by zcream** [comment]
HTML render and HTML view are functionally separate operations. The browser window be customized by a user, if the HTML render is independent of the the Viewer gui. Also the html buffer can be preprocessed of post processed as needed.
