### ISSUE TITLE
WebView2.h is not in the repo

### ISSUE THREAD

**Issue by morgan3d** [MichaelKim/webview#2]
This is included in the WEBVIEW_EDGE path but not committed to the repo.

**Comment by MichaelKim** [comment]
`WebView2.h` comes with the new [Webview 2 SDK](https://www.nuget.org/packages/Microsoft.Web.WebView2/) and should work once installed. There's also documentation [here](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32) for more detailed info on the new WebView2.

Alternatively, https://github.com/webview/webview seems to the package directly. You can see the header file [here](https://github.com/webview/webview/blob/843c3aaba6a14f11b37db2c58879534f253f37d5/script/WebView2.h).
