### ISSUE TITLE
Build without Visual Studio

### ISSUE THREAD

**Issue by diegofazio** [MichaelKim/webview#5]
Hi, I would like to compile the simple/main.cpp example without Visual Studio. With MSVC cl.exe from command line. 
It's possible?

Thanks
Diego.

**Comment by MichaelKim** [comment]
With the new Chromium-based Edge, you'd need access to the WebView2 library. Using Visual Studio, this is normally done by installing the SDK through [NuGet](https://www.nuget.org/packages/Microsoft.Web.WebView2). Here's how I got it working by calling `cl.exe` directly:

1. Make sure you have the new Edge installed (beta, dev, or canary) or get the [runtime directly](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) (I haven't tried this, but I imagine it should still work).
2. Download the [WebView2 package](https://www.nuget.org/packages/Microsoft.Web.WebView2), extract the files by renaming it to a `.zip`, and grab the header from `.\build\native\include\WebView2.h` and the library from `.\build\native\x86\WebView2LoaderStatic.lib`.
    - For dynamic linking, use `WebView2Loader.dll.lib` and make sure `WebView2Loader.dll` is located with your executable when running.
3. Download the [Windows Implementation Libraries package](https://www.nuget.org/packages/Microsoft.Windows.ImplementationLibrary/), extract the files, and grab the header files under `.\include\`.
4. Run `cl basic.cpp /DWEBVIEW_EDGE /EHsc /std:c++17 /link WebView2LoaderStatic.lib user32.lib Version.lib Advapi32.lib Shell32.lib`.

Let me know if this works for you!

**Comment by diegofazio** [comment]
Thanks! I'll try. Webview2 official works perfect with windows 7. Does your webview works with it? Zerge and Soundux version does not. https://github.com/Soundux/webviewpp/issues/4
Do you know why? 
Here you have a simple webview2 sample which works perfect on Win7/8/10 x86/x64 build with cl.exe
Thanks Again!

**Comment by MichaelKim** [comment]
This webview is fairly simple and those other two webviews probably have additional features that are causing the issue (i.e. calling some additional Windows API that only work on Win10).

As far as I know, this webview should be fine with `WEBVIEW_EDGE` for Win 7/8/10. With a new Win7 VM, I had to install VS Build Tools along with the C++ build tools (+Win10 SDK), and the basic example seemed to work properly:

![image](https://user-images.githubusercontent.com/8509052/124372505-4e127f80-dc58-11eb-908b-fe8180a24bd0.png)

**Comment by diegofazio** [comment]
Works PERFECT! Thanks and great job!
