### ISSUE TITLE
Windows 7 not more compatible with new Updates.

### ISSUE THREAD

**Issue by diegofazio** [MichaelKim/webview#8]
Hi Michael, adding the #pragma comment(lib, "windowsapp") using WEBVIEW_EDGE make not more compatible with windows 7. Why do you need it?

**Comment by MichaelKim** [comment]
Just pushed some more changes along with removing that pragma from WEBVIEW_EDGE. Could you pull and try again?

**Comment by diegofazio** [comment]
It works. But why did you included it?

**Comment by MichaelKim** [comment]
I think I added it to avoid linking some libraries since `windowsapp.lib` covers most things, but looks like it doesn't work on Windows 7. Guess it makes sense considering it's for linking Windows 10 APIs.

**Comment by MichaelKim** [comment]
@diegofazio Just a heads up: if you're manually linking with the latest update, you might also need to also link `gdi32.lib`.
