### ISSUE TITLE
WebView2.h not found

### ISSUE THREAD

**Issue by kuyoonjo** [MichaelKim/webview#9]
```
...
./include/gui/webview.h:45:10: fatal error: 'WebView2.h' file not found
...
```

**Comment by MichaelKim** [comment]
You need to get the [WebView2 SDK](https://www.nuget.org/packages/Microsoft.Web.WebView2) from NuGet. You'll probably also need the [WIL package](https://www.nuget.org/packages/Microsoft.Windows.ImplementationLibrary/) too. There's a few ways to do this:
- If you use Visual Studio, add the packages to your solution.
- If you use the provided CMake config, it should automatically install them, provided you have the NuGet CLI.
- Manually download the package and include / link the files yourself. See the [build docs](https://github.com/MichaelKim/webview/blob/master/docs/build.md#chromium-edge) for more info.

**Comment by kuyoonjo** [comment]
Thanks.
